mystery_items = [
    {"type": "joke", "content": "Why don't skeletons fight each other? They don't have the guts."},
    {"type": "quote", "content": "“Time is an illusion. Lunchtime doubly so.” – Douglas Adams"},
    {"type": "ascii_art", "content": "(\\_/)\n( •_•)\n/>🍪"},
    {"type": "fake_error", "content": "Error 418: The API is a teapot. Try again after tea."},
    {"type": "fact", "content": "Bananas are berries, but strawberries aren't."},
    {"type": "emoji_story", "content": "🧙‍♂️➡️🐉🔥🏰💍🗻"},
    {"type": "mystery_link", "content": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"},
    {"type": "sound_effect", "content": "🔊 BOOOOM! (imagine it, we don’t serve actual audio yet)"},
    {"type": "riddle", "content": "What has keys but can't open locks? A piano."},
    {"type": "weird_law", "content": "In Switzerland, it’s illegal to own just one guinea pig. They get lonely."},
    {"type": "fake_app_idea", "content": "App Name: 'Snaccident' – tracks how many chips you accidentally ate."},
    {"type": "inspirational_but_useless", "content": "Believe in yourself. Even your WiFi signal goes further when you do."},
    {"type": "invented_word", "content": "Glumbuzzle (n.): The face you make when someone eats your fries."},
    {"type": "superpower", "content": "You now have the power to refill empty pens. Use it wisely."},
    {"type": "universal_truth", "content": "Everyone has a drawer full of random cables they refuse to throw away."},
    {"type": "haiku", "content": "Code is like a poem\nIndents whisper like secrets\nBug wakes in the night"},
    {"type": "mystery_emoji_combo", "content": "🦖📦🎈🥓🎩 — interpret this at your own risk."},
    {"type": "animal_fact", "content": "Octopuses have three hearts and blue blood. They are basically underwater goths."},
    {"type": "unexpected_history", "content": "Napoleon was once attacked by a horde of bunnies during a hunting trip."},
]
